version: '2'

services:
  token-introspector:
    build:
      context: .
      dockerfile: Dockerfile
    image: syncforscience/token-introspector
    expose: ["5000"]
    environment:
     - API_SERVER=http://smart:5000/api/fhir
    networks:
     - internal

networks:
  internal:
    driver: bridge
